name: Nest.JS CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-dept: 0
      - name: Use m Nest.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM install, build and test
        run: |
          npm install
          npm run start:dev
          npm run test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET:   ${{ secrets.JWT_SECRET }}
  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: xch4rt/render-reploy@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}